CREATE TABLE roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    PRIMARY KEY (role_id)
);

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(60) NOT NULL,
    password VARCHAR(255) NOT NULL,
    status INT CHECK (status in (1, 0)) NOT NULL DEFAULT 1,
    PRIMARY KEY (user_id),
    CONSTRAINT unique_email UNIQUE (email)
);

CREATE TABLE users_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL,
    FOREIGN KEY (role_id) REFERENCES roles(role_id) ON DELETE SET NULL
);

CREATE TABLE addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    street_name VARCHAR(255) NOT NULL,
    number VARCHAR(10),
    complement VARCHAR(100),
    district VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(15) NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (address_id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE NO ACTION ON UPDATE NO ACTION
);